import assert from 'node:assert/strict';
import {makePlan} from './bankroll.ts';
const now=Date.parse('2026-09-30T16:00:00Z');
const limits={bank:10,perBet:1,total:3,minimum:.1,haircut:5,open:0};
const price={fixture_id:'a',player:'A',match:'A vs B',probability:.75,odds:2,start_at:'2026-10-01T12:00:00Z',observed_at:'2026-09-30T15:00:00Z',url:'',tour:'ATP'};
const result=makePlan([price,{...price,player:'B'},...['b','c','d'].map(fixture_id=>({...price,fixture_id}))],limits,now);
assert.equal(result.reduce((sum,r)=>Math.round((sum+r.simulated)*100)/100,0),.3);
assert.equal(result.filter(r=>r.simulated>0 && r.fixture_id==='a').length,1);
assert.ok(result.every(r=>r.real===0 && r.simulated<=.1));
assert.equal(makePlan([price],{...limits,minimum:.5},now)[0].simulated,0);
assert.equal(makePlan([price],{...limits,open:.3},now)[0].simulated,0);
assert.equal(makePlan([{...price,observed_at:'2026-09-29T15:00:00Z'}],limits,now)[0].simulated,0);
assert.equal(makePlan([{...price,start_at:'2026-09-30T12:00:00Z'}],limits,now)[0].simulated,0);
assert.equal(makePlan([{...price,probability:NaN}],limits,now)[0].simulated,0);
assert.throws(()=>makePlan([price],{...limits,bank:NaN},now));
console.log('bankroll ok');
