"use client";
import {decimal, pct} from "../lib/api";

export type Offer = {id: string; bookmaker: string; selection: string; decimal_odds: number; observed_at: string; source_ref: string; probability: number | null; fair_odds: number | null; model_price_edge: number | null; no_vig_market_probability: number | null};
export type Fixture = {id: string; tour: string; tournament: string; start_at: string; player_a: string; player_b: string; probability_a: number | null; quality: {surface?: string; surface_known?: boolean; exact_player_match?: boolean; reason?: string; rank_a?: string; rank_b?: string; round?: string}; analysis?: Record<string, number | null>; source_url: string; offers: Offer[]; status: string};
const surfaces: Record<string,string> = {Hard:"Duro",Clay:"Terra batida",Grass:"Relva",Carpet:"Carpete"};
const time = (value: string) => new Intl.DateTimeFormat("pt-PT",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Lisbon"}).format(new Date(value));

export function GameCard({item,onAdd}: {item: Fixture; onAdd: (item: Fixture,offer: Offer) => void}) {
  const p = item.probability_a != null && Number.isFinite(item.probability_a) && item.probability_a >= 0 && item.probability_a <= 1 ? item.probability_a : null;
  const favorite = p == null || p === .5 ? null : p > .5 ? "a" : "b";
  const aPct = p == null ? null : Math.round(p*1000)/10;
  const chances = aPct == null ? [null,null] : [aPct/100,(100-aPct)/100];
  return <article className="game-card" aria-label={`${item.player_a} contra ${item.player_b}`}>
    <header className="game-meta"><div><span className="game-tour">{item.tour}</span><span>{item.tournament}</span></div><time dateTime={item.start_at}>{time(item.start_at)}<small>Lisboa</small></time></header>
    <p className="game-round">{item.quality.round?.replace(/Round (\d+)/,"Ronda $1").replace("Quarterfinals","Quartos de final").replace("Semifinals","Meias-finais") || "Ronda por confirmar"} · {surfaces[item.quality.surface || ""] || "Superfície por confirmar"}</p>
    <div className="game-players">{[item.player_a,item.player_b].map((name,i) => <div className={`game-player ${favorite===(i===0 ? "a" : "b") ? "game-favorite" : ""}`} key={`${i}:${name}`}>
      <span className="game-player-state">{p==null ? "Sem estimativa" : favorite===(i===0 ? "a" : "b") ? "Mais provável" : favorite==null ? "Probabilidades iguais" : "Também pode ganhar"}</span><h3>{name}</h3><strong aria-label={`${name}: ${chances[i] == null ? "probabilidade indisponível" : pct(chances[i])}`}>{pct(chances[i])}</strong><span className="game-chance-label">probabilidade estimada</span></div>)}</div>
    {p!=null ? <><div className={`game-probability-track favorite-${favorite || "equal"}`} aria-hidden="true"><span style={{width:`${aPct}%`}}/><span style={{width:`${100-(aPct ?? 0)}%`}}/></div><p className="game-reading">{favorite ? <>O modelo favorece <strong>{favorite==="a" ? item.player_a : item.player_b}</strong>. Diferença de {decimal(Math.abs(2*p-1)*100,1)} pontos percentuais.</> : "O modelo estima um confronto equilibrado, sem favorito."}</p></> : <p className="game-unavailable">{item.quality.reason || "A identificação dos jogadores ainda não permite uma estimativa fiável."}</p>}
    <details className="game-details"><summary>Contexto, dados e origem<span aria-hidden="true">+</span></summary>{item.analysis ? <><p>Informação histórica disponível antes do encontro. O arquivo termina em maio de 2026; pode não refletir a forma atual.</p><div className="game-context-players"><span>{item.player_a}</span><span>{item.player_b}</span></div><dl className="game-context"><div><dt>Elo geral</dt><dd>{decimal(item.analysis.elo_a,0)} / {decimal(item.analysis.elo_b,0)}</dd></div><div><dt>Pontos ganhos no serviço</dt><dd>{pct(item.analysis.serve_a)} / {pct(item.analysis.serve_b)}</dd></div><div><dt>Vitórias nos últimos dez jogos</dt><dd>{pct(item.analysis.form_a)} / {pct(item.analysis.form_b)}</dd></div><div><dt>Jogos nos 30 dias anteriores</dt><dd>{item.analysis.load_30d_a ?? "—"} / {item.analysis.load_30d_b ?? "—"}</dd></div></dl></> : <p>A estimativa aparece quando os jogadores e o nível da prova estão confirmados para o modelo.</p>}<p>Cabeças de série: {item.quality.rank_a || "—"} / {item.quality.rank_b || "—"}. Estes valores não são rankings mundiais.</p><a className="text-link" href={item.source_url} target="_blank" rel="noreferrer">Confirmar encontro na ESPN ↗</a></details>
    <details className="game-details game-odds"><summary>{item.offers.length ? `Comparar ${item.offers.length} cotações` : "Cotações e calculadora"}<span aria-hidden="true">+</span></summary>{item.offers.length ? <div className="offer-list">{item.offers.map(offer => <div className="offer-row" key={offer.id}><span>{offer.selection}<small>{offer.bookmaker} · {time(offer.observed_at)}</small></span><strong>{decimal(offer.decimal_odds)}</strong><span>{offer.probability==null ? "sem modelo" : `${pct(offer.probability)} modelo`}</span><button className="button-secondary" onClick={() => onAdd(item,offer)} aria-label={`Usar ${offer.selection} a ${decimal(offer.decimal_odds)} na calculadora`}>Usar</button></div>)}</div> : <p>Não existem cotações recentes verificadas para este encontro. As probabilidades acima são estimativas do modelo.</p>}</details>
  </article>;
}
