"use client";
import {useMemo, useState} from "react";
import Link from "next/link";
import {Metrics, decimal, pct} from "../lib/api";

type Pair = {baseline: Metrics; selected: Metrics};
type Period = Pair & {paired: {improvement: number; bootstrap_95: number[]; n_tournaments: number}; subgroups: Record<string, Pair>; reliability: {from: number; to: number; n: number; predicted: number | null; observed: number | null}[]};
export type Analysis = {incremental_vs_previous?: {improvement:number;bootstrap_95:number[]}; selected: string; created_at: string; new_configurations: number; shuffle_controls: number; yearly: Record<string, Pair>; periods: Record<string, Period>; candidates: {name: string; mean_annual_brier: number; round: number}[]; limitations: string[]; forward: {n: number; n_matches?: number; settled: number; forecasts: {fixture_id: string; version: string; player_a: string; player_b: string; start_at: string; as_of: string; baseline: number; selected: number; settled: boolean}[]}};
const labels: Record<string, string> = {v4: "Referência v4", v5_layoff: "Referência com inatividade", dynamic: "Aptidão e incerteza", point_global: "Serviço ajustado à oposição", point_surface: "Serviço por superfície", margin: "Margens dos sets", mechanistic: "Cadeia ponto–jogo–set", point_mechanistic: "Serviço + cadeia de jogo", all: "Aptidão, serviço e margens", metadata: "Idade, altura e ranking", all_metadata: "Métodos combinados + metadados", all_by_tour: "Métodos combinados · ATP/WTA separados", all_metadata_by_tour: "Metadados · ATP/WTA separados", all_metadata_context: "Métodos combinados + formato", markov_standalone: "Cadeia de Markov isolada", dynamic_standalone: "Aptidão dinâmica isolada", service_detail: "Primeiro e segundo serviço", pressure: "Pressão em break points", network: "Adversários comuns e confrontos diretos", multiscale: "Forma em duas escalas + carga", style: "Geometria de estilos", all_dynamics: "Todas as hipóteses dinâmicas", recency_730d: "Métodos combinados · maior peso ao recente", hist_boost: "Alternativa de árvores regularizadas"};
const modelName = (name: string) => labels[name] || name.replaceAll("_", " ");
const timestamp = (value: string) => new Intl.DateTimeFormat("pt-PT", {day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Lisbon"}).format(new Date(value));
const groupName: Record<string, string> = {Hard: "Duro", Clay: "Terra batida", Grass: "Relva"};

function Evolution({yearly}: {yearly: Record<string, Pair>}) {
  const items = Object.entries(yearly);
  const values = items.flatMap(([, p]) => [p.baseline.brier ?? 0, p.selected.brier ?? 0]);
  const low = Math.min(...values)-.001, high = Math.max(...values)+.001;
  const x = (i: number) => 50 + i*650/Math.max(items.length-1, 1);
  const y = (v: number) => 30+(high-v)/(high-low)*160;
  const path = (key: "baseline" | "selected") => items.map(([, p], i) => `${i ? "L" : "M"}${x(i)},${y(p[key].brier ?? 0)}`).join(" ");
  return <figure className="research-chart"><svg viewBox="0 0 740 245" role="img" aria-labelledby="evolution-title evolution-description"><title id="evolution-title">Brier anual: referência v4 e candidato</title><desc id="evolution-description">Quanto mais baixo, melhor. A tabela por ano contém os valores exatos; 2024 em diante é diagnóstico já consultado.</desc><rect x={x(4)+650/14} y="18" width={740-x(4)-650/14-15} height="185" className="diagnostic-area"/>{[0,1,2,3].map(i => {const v=low+(high-low)*i/3; return <g key={i}><line x1="50" x2="710" y1={y(v)} y2={y(v)} className="chart-grid"/><text x="42" y={y(v)+4} textAnchor="end">{v.toFixed(3)}</text></g>;})}<path d={path("baseline")} className="chart-baseline"/><path d={path("selected")} className="chart-selected"/>{items.map(([year,pair],i) => <g key={year}><text x={x(i)} y="225" textAnchor="middle">{year}</text><circle cx={x(i)} cy={y(pair.selected.brier ?? 0)} r="4" className="chart-point"><title>{year}: referência {decimal(pair.baseline.brier,6)}, candidato {decimal(pair.selected.brier,6)}</title></circle></g>)}</svg><figcaption><span className="legend-reference">Referência v4</span><span className="legend-selected">Candidato</span><span>Área sombreada: diagnóstico</span></figcaption></figure>;
}

export function ResearchDashboard({analysis}: {analysis: Analysis}) {
  const [period,setPeriod]=useState("diagnostic");
  const [query,setQuery]=useState("");
  const [sort,setSort]=useState("brier");
  const candidates=useMemo(() => analysis.candidates.filter(c => modelName(c.name).toLocaleLowerCase("pt-PT").includes(query.toLocaleLowerCase("pt-PT"))).sort((a,b) => sort==="round" ? a.round-b.round || a.mean_annual_brier-b.mean_annual_brier : a.mean_annual_brier-b.mean_annual_brier),[analysis,query,sort]);
  const data=analysis.periods[period];
  function download() {const url=URL.createObjectURL(new Blob([JSON.stringify(analysis,null,2)],{type:"application/json"})); const link=document.createElement("a"); link.href=url; link.download="tennis-quant-investigacao.json"; link.click(); setTimeout(() => URL.revokeObjectURL(url),1000);}
  return <>
    <section className="research-intro"><div><span className="state-pill">CANDIDATO EM INVESTIGAÇÃO</span><h2>{modelName(analysis.selected)}</h2><p>{analysis.new_configurations} novas configurações, {analysis.shuffle_controls} controlos baralhados e oito janelas anuais. Seleção em 2019–2023; os anos posteriores servem de diagnóstico.</p><button className="button-secondary" onClick={download}>Descarregar análise</button></div><dl className="research-status"><div><dt>Agenda diária</dt><dd>Referência v4</dd></div><div><dt>Confirmação futura</dt><dd>{analysis.forward.settled} / {analysis.forward.n} previsões com resultado</dd></div><div><dt>Análise atualizada</dt><dd>{timestamp(analysis.created_at)}</dd></div></dl></section>
    <section className="panel research-section" aria-labelledby="comparison-title"><div className="research-section-heading"><div><h2 id="comparison-title">O que melhorou</h2><p>Os dois modelos usam o mesmo conjunto de jogos e as mesmas janelas.</p></div><div className="day-tabs" aria-label="Período da comparação"><button aria-pressed={period==="development"} className={period==="development" ? "selected" : ""} onClick={() => setPeriod("development")}>Desenvolvimento</button><button aria-pressed={period==="diagnostic"} className={period==="diagnostic" ? "selected" : ""} onClick={() => setPeriod("diagnostic")}>Diagnóstico</button></div></div><div className="table-scroll"><table className="data-table research-table"><caption>{period==="development" ? "2019–2023 · desenvolvimento" : "2024–maio 2026 · diagnóstico já consultado"} · {data.baseline.n.toLocaleString("pt-PT")} jogos</caption><thead><tr><th scope="col">Métrica</th><th scope="col">Referência v4</th><th scope="col">Candidato</th><th scope="col">Como ler</th></tr></thead><tbody><tr><th scope="row">Brier</th><td>{decimal(data.baseline.brier,6)}</td><td className="research-emphasis">{decimal(data.selected.brier,6)}</td><td>Menor erro probabilístico é melhor</td></tr><tr><th scope="row">Log loss</th><td>{decimal(data.baseline.log_loss,6)}</td><td>{decimal(data.selected.log_loss,6)}</td><td>Penaliza confiança errada</td></tr><tr><th scope="row">Acerto</th><td>{pct(data.baseline.accuracy,2)}</td><td>{pct(data.selected.accuracy,2)}</td><td>Não mede a qualidade das probabilidades</td></tr><tr><th scope="row">Erro de calibração</th><td>{decimal(data.baseline.ece_10,6)}</td><td>{decimal(data.selected.ece_10,6)}</td><td>ECE em dez intervalos; menor é melhor</td></tr></tbody></table></div><p className="research-evidence">Melhoria de Brier: <strong>{decimal(data.paired.improvement,6)}</strong>. Bootstrap 95%: [{decimal(data.paired.bootstrap_95[0],6)}; {decimal(data.paired.bootstrap_95[1],6)}], por {data.paired.n_tournaments} torneios.</p><p className="fine-print">Intervalo retrospectivo. Seleção entre muitas hipóteses e dependência entre torneios limitam a interpretação. Não demonstra lucro nem confirmação futura.</p></section>
    {analysis.incremental_vs_previous && <div className="notice amber"><strong>Ganho incremental ainda incerto</strong><span>Face ao candidato da ronda anterior, a melhoria de Brier é {decimal(analysis.incremental_vs_previous.improvement,6)}; intervalo 95% [{decimal(analysis.incremental_vs_previous.bootstrap_95[0],6)}; {decimal(analysis.incremental_vs_previous.bootstrap_95[1],6)}]. O intervalo inclui zero. O novo candidato continua em avaliação paralela.</span></div>}
    <section className="panel research-section"><div className="research-section-heading"><div><h2>Consistência entre anos</h2><p>Inclui os anos em que o ganho é menor.</p></div></div><Evolution yearly={analysis.yearly}/><details className="research-details"><summary>Ver os valores por ano</summary><div className="table-scroll"><table className="data-table research-table"><thead><tr><th scope="col">Ano</th><th scope="col">Jogos</th><th scope="col">Brier v4</th><th scope="col">Brier candidato</th><th scope="col">Acerto v4</th><th scope="col">Acerto candidato</th></tr></thead><tbody>{Object.entries(analysis.yearly).map(([year,pair]) => <tr key={year}><th scope="row">{year}{Number(year)>=2024 ? " · diagnóstico" : ""}</th><td>{pair.baseline.n.toLocaleString("pt-PT")}</td><td>{decimal(pair.baseline.brier,6)}</td><td>{decimal(pair.selected.brier,6)}</td><td>{pct(pair.baseline.accuracy,2)}</td><td>{pct(pair.selected.accuracy,2)}</td></tr>)}</tbody></table></div></details></section>
    <div className="research-pair"><section className="panel research-section"><h2>Circuitos e superfícies</h2><div className="table-scroll"><table className="data-table research-table research-compact"><thead><tr><th scope="col">Grupo</th><th scope="col">Jogos</th><th scope="col">Brier v4</th><th scope="col">Candidato</th></tr></thead><tbody>{Object.entries(data.subgroups).map(([name,pair]) => <tr key={name}><th scope="row">{groupName[name] || name}</th><td>{pair.baseline.n.toLocaleString("pt-PT")}</td><td>{decimal(pair.baseline.brier,4)}</td><td>{decimal(pair.selected.brier,4)}</td></tr>)}</tbody></table></div></section><section className="panel research-section"><h2>Confiança versus realidade</h2><p>A previsão do favorito deve aproximar-se da sua frequência de vitória.</p><div className="table-scroll"><table className="data-table research-table research-compact"><thead><tr><th scope="col">Confiança</th><th scope="col">Jogos</th><th scope="col">Previsto</th><th scope="col">Observado</th></tr></thead><tbody>{data.reliability.map(bin => <tr key={bin.from}><th scope="row">{pct(bin.from,0)}–{pct(bin.to,0)}</th><td>{bin.n.toLocaleString("pt-PT")}</td><td>{pct(bin.predicted,1)}</td><td>{pct(bin.observed,1)}</td></tr>)}</tbody></table></div></section></div>
    <section className="panel research-section"><div className="research-section-heading"><div><h2>Registo de experiências</h2><p>Resultados favoráveis e desfavoráveis, ordenados pelo critério de seleção.</p></div></div><div className="research-filters"><label>Procurar hipótese<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ex.: serviço, ranking, adversários"/></label><label>Ordenar por<select value={sort} onChange={e => setSort(e.target.value)}><option value="brier">Brier médio anual</option><option value="round">Ronda de investigação</option></select></label><span aria-live="polite">{candidates.length} configurações</span></div><div className="table-scroll"><table className="data-table research-table"><thead><tr><th scope="col">Hipótese</th><th scope="col">Ronda</th><th scope="col">Brier médio anual 2019–2023 ↓</th><th scope="col">Estado</th></tr></thead><tbody>{candidates.map(c => <tr key={c.name} className={c.name===analysis.selected ? "research-selected" : ""}><th scope="row">{modelName(c.name)}</th><td>{c.round}</td><td>{decimal(c.mean_annual_brier,6)}</td><td>{c.name===analysis.selected ? "Candidato selecionado" : "Comparado"}</td></tr>)}</tbody></table></div>{!candidates.length && <p role="status">Não existem hipóteses com esse nome. Limpa a pesquisa para ver todas.</p>}</section>
    <section className="panel research-section"><h2>Acompanhamento futuro</h2><p>Previsões guardadas antes do início do jogo, para comparar os dois modelos com o mesmo resultado.</p>{analysis.forward.forecasts.length ? <div className="table-scroll"><table className="data-table research-table"><thead><tr><th scope="col">Jogo</th><th scope="col">Guardado</th><th scope="col">V4 · jogador A</th><th scope="col">Candidato · jogador A</th><th scope="col">Estado</th></tr></thead><tbody>{analysis.forward.forecasts.map(item => <tr key={`${item.version}:${item.fixture_id}`}><th scope="row">{item.player_a}<span className="research-versus">vs. {item.player_b}</span></th><td>{timestamp(item.as_of)}</td><td>{pct(item.baseline)}</td><td>{pct(item.selected)}</td><td>{item.settled ? "Resultado recolhido" : "A aguardar resultado verificável"}</td></tr>)}</tbody></table></div> : <p>Ainda não existem previsões congeladas elegíveis.</p>}<p className="fine-print">{analysis.forward.n} previsões; {analysis.forward.n_matches ?? analysis.forward.n} encontros distintos; {analysis.forward.settled} resultados provisórios. A amostra ainda não confirma qualidade prospectiva.</p></section>
    <aside className="research-pending"><h2>O que falta confirmar</h2><ul>{analysis.limitations.map(limit => <li key={limit}>{limit}</li>)}<li>Acumular jogos futuros e verificar a estabilidade da calibração.</li></ul><Link className="text-link" href="/dados">Consultar cobertura e fontes →</Link></aside><details className="research-details"><summary>Origem das metodologias e limites</summary><p>As hipóteses combinam classificação dinâmica, serviço ajustado à oposição, margens, metadados e formato. São adaptações próprias sujeitas a teste.</p><p><a className="text-link" href="https://www.glicko.net/research/glicko.pdf" target="_blank" rel="noreferrer">Aptidão dinâmica · Glickman</a> · <a className="text-link" href="https://journals.sagepub.com/doi/10.3233/JSA-200345" target="_blank" rel="noreferrer">Previsão de serviço · Gollub</a></p></details>
  </>;
}
