"use client";

import { useEffect, useState } from "react";
import { Metrics, decimal, getJSON, pct } from "../../lib/api";

type ModelReport = Record<string, unknown> & {selected_by_validation?: string; splits?: Record<string, number>; betting_backtest?: string; comparison?: {paired_comparison?: {xgboost_vs_logistic?: {cluster_bootstrap_95: number[]}}; by_group?: Record<string, Record<string, number>>}};
const families = [{id: "elo", name: "Elo", desc: "Classificação global e de superfície; referência estrutural."}, {id: "logistic", name: "Logística", desc: "Modelo linear simétrico com variáveis pré-torneio."}, {id: "xgboost", name: "XGBoost", desc: "Árvores com profundidade limitada e regularização pré-definida."}];

export default function Models() {
  const [report, setReport] = useState<ModelReport | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => {getJSON<ModelReport>("/api/models").then(setReport).catch(() => setError(true));}, []);
  return <><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> VALIDAÇÃO / PROBABILIDADE</div><h1>Modelos<span className="heading-dot">.</span></h1><p>Três famílias comparadas em períodos separados. O teste fora da amostra não decide o vencedor.</p></div><div className="heading-stamp">04 <span>/ 05</span></div></div>
    {error && <div className="notice danger">A API não está disponível.</div>}
    <div className="timeline"><div><span>01</span><strong>2015–2021</strong><small>TREINO</small></div><i>→</i><div><span>02</span><strong>2022</strong><small>CALIBRAÇÃO</small></div><i>→</i><div><span>03</span><strong>2023</strong><small>SELEÇÃO</small></div><i>→</i><div className="highlight"><span>04</span><strong>2024–2026</strong><small>TESTE OOS</small></div></div>
    <div className="model-cards">{families.map(f => {const d = report?.[f.id] as {version?: string; validation?: Metrics; test_oos?: Metrics} | undefined; return <section className={`panel model-card ${report?.selected_by_validation === f.id ? "selected" : ""}`} key={f.id}><div className="model-card-head"><span className="overline">{f.name.toUpperCase()}</span>{report?.selected_by_validation === f.id && <span className="mini-tag accent">SELECIONADO EM 2023</span>}</div><h2>{f.name}</h2><p>{f.desc}</p><div className="model-card-metrics"><div><span>BRIER · VALIDAÇÃO</span><strong>{decimal(d?.validation?.brier, 4)}</strong></div><div><span>BRIER · TESTE OOS</span><strong>{decimal(d?.test_oos?.brier, 4)}</strong></div><div><span>LOG LOSS · TESTE OOS</span><strong>{decimal(d?.test_oos?.log_loss, 4)}</strong></div><div><span>ACERTO · TESTE OOS</span><strong>{pct(d?.test_oos?.accuracy)}</strong></div></div><small className="model-version">{d?.version || "Modelo por treinar"}</small></section>;})}</div>
    {report?.comparison?.paired_comparison?.xgboost_vs_logistic && <div className="notice amber"><strong>Vantagem ainda incerta</strong><span>O intervalo bootstrap por torneio da melhoria de Brier do XGBoost face à logística inclui zero ({decimal(report.comparison.paired_comparison.xgboost_vs_logistic.cluster_bootstrap_95[0], 6)} a {decimal(report.comparison.paired_comparison.xgboost_vs_logistic.cluster_bootstrap_95[1], 6)}). Em 2025, a logística teve Brier inferior. Nenhum dos modelos está aprovado para sinais.</span></div>}
    <section className="panel methodology"><div className="section-top"><div><span className="overline">PROTOCOLO</span><h2>Como foi avaliado</h2></div><span className="state-pill">PREDICTION ONLY</span></div><div className="method-grid"><div><strong>01 / Sem informação futura</strong><p>As features são calculadas antes de atualizar o estado com os resultados de cada data de início de torneio.</p></div><div><strong>02 / Simetria</strong><p>O treino inclui as duas orientações do jogo para reduzir dependência da ordem A/B.</p></div><div><strong>03 / Calibração separada</strong><p>Ajuste sigmoid em 2022. A seleção por Brier usa 2023. O teste 2024+ não é usado para escolher parâmetros.</p></div><div><strong>04 / Sem resultado de apostas</strong><p>ROI, CLV, custos e gates de estratégia requerem odds anteriores ao jogo com timestamp e hora real de início.</p></div></div><div className="panel-note">Tentativas de família: 3. Parâmetros pré-definidos, sem sweep. Nenhuma estratégia foi aprovada. A seleção entre famílias continua sujeita a confirmação futura.</div></section>
  </>;
}

