"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Metrics, decimal, getJSON, pct } from "../../lib/api";

type CandidatePeriod = {baseline: Metrics; challenger: Metrics; paired: {improvement: number; bootstrap_95: number[]; n_tournaments: number}};
type LayoffResearch = {version: string; yearly: Record<string, {baseline: Metrics; challenger: Metrics}>; development_2019_2023: CandidatePeriod; diagnostic_2024_2026: CandidatePeriod};
type ModelReport = Record<string, unknown> & {selected_by_validation?: string; operational_version?: string; splits?: Record<string, number>; betting_backtest?: string; layoff_research?: LayoffResearch; comparison?: {paired_comparison?: {xgboost_vs_logistic?: {cluster_bootstrap_95: number[]}}; by_group?: Record<string, Record<string, number>>}};
const families = [{id: "elo", name: "Elo", desc: "Classificação global e de superfície; referência estrutural."}, {id: "logistic", name: "Logística", desc: "Modelo linear simétrico com variáveis pré-torneio."}, {id: "xgboost", name: "XGBoost", desc: "Árvores com profundidade limitada e regularização pré-definida."}];

export default function Models() {
  const [report, setReport] = useState<ModelReport | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => {getJSON<ModelReport>("/api/models").then(setReport).catch(() => setError(true));}, []);
  return <><div className="page-heading"><div><h1>Modelos<span className="heading-dot">.</span></h1><p>Famílias, variáveis e calibração comparadas em janelas cronológicas. Os candidatos continuam em investigação.</p></div><Link href="/backtests" className="button-primary">Ver backtests →</Link></div>
    {error && <div className="notice danger">A API não está disponível.</div>}
    <div className="timeline"><div><span>01</span><strong>2015–2021</strong><small>TREINO</small></div><i>→</i><div><span>02</span><strong>2022</strong><small>CALIBRAÇÃO</small></div><i>→</i><div><span>03</span><strong>2023</strong><small>SELEÇÃO</small></div><i>→</i><div className="highlight"><span>04</span><strong>2024–2026</strong><small>DIAGNÓSTICO</small></div></div>
    <div className="model-cards">{families.map(f => {const d = report?.[f.id] as {version?: string; validation?: Metrics; test_oos?: Metrics} | undefined; return <section className={`panel model-card ${report?.selected_by_validation === f.id ? "selected" : ""}`} key={f.id}><div className="model-card-head"><span className="overline">{f.name.toUpperCase()}</span>{report?.selected_by_validation === f.id && <span className="mini-tag accent">SELECIONADO EM 2023</span>}</div><h2>{f.name}</h2><p>{f.desc}</p><div className="model-card-metrics"><div><span>BRIER · VALIDAÇÃO</span><strong>{decimal(d?.validation?.brier, 4)}</strong></div><div><span>BRIER · DIAGNÓSTICO</span><strong>{decimal(d?.test_oos?.brier, 4)}</strong></div><div><span>LOG LOSS · DIAGNÓSTICO</span><strong>{decimal(d?.test_oos?.log_loss, 4)}</strong></div><div><span>ACERTO · DIAGNÓSTICO</span><strong>{pct(d?.test_oos?.accuracy)}</strong></div></div><small className="model-version">{d?.version || "Modelo por treinar"}</small></section>;})}</div>
    {report?.layoff_research && <section className="panel backtest-section"><div className="section-top"><div><span className="overline">MODELO DESAFIANTE · INVESTIGAÇÃO</span><h2>Tempo desde o último torneio</h2></div><span className="state-pill">SEM PROMOÇÃO</span></div><p>Uma variável adicional mede a diferença entre os intervalos de inatividade dos dois jogadores, limitada a 365 dias. O XGBoost e a calibração mantêm os parâmetros atuais. O modelo diário continua a usar a versão anterior.</p><div className="backtest-strip"><div><span>Brier 2019–2023 · atual</span><strong>{decimal(report.layoff_research.development_2019_2023.baseline.brier, 4)}</strong></div><div><span>Brier 2019–2023 · desafiante</span><strong>{decimal(report.layoff_research.development_2019_2023.challenger.brier, 4)}</strong></div><div><span>Melhoria pareada</span><strong>{decimal(report.layoff_research.development_2019_2023.paired.improvement, 6)}</strong></div></div><p className="fine-print">Bootstrap por torneio, 95%: {decimal(report.layoff_research.development_2019_2023.paired.bootstrap_95[0], 6)} a {decimal(report.layoff_research.development_2019_2023.paired.bootstrap_95[1], 6)}. Em 2024–2026 a melhoria é {decimal(report.layoff_research.diagnostic_2024_2026.paired.improvement, 6)}; intervalo {decimal(report.layoff_research.diagnostic_2024_2026.paired.bootstrap_95[0], 6)} a {decimal(report.layoff_research.diagnostic_2024_2026.paired.bootstrap_95[1], 6)}, incluindo zero. Este período já foi consultado durante o desenvolvimento.</p><div className="table-scroll"><table className="data-table backtest-table"><thead><tr><th>Ano</th><th>Jogos</th><th>Brier atual ↓</th><th>Brier desafiante ↓</th><th>Diferença</th></tr></thead><tbody>{Object.entries(report.layoff_research.yearly).map(([year, pair]) => <tr key={year}><td>{year}{Number(year) >= 2024 ? " · diagnóstico" : ""}</td><td>{pair.baseline.n.toLocaleString("pt-PT")}</td><td>{decimal(pair.baseline.brier, 4)}</td><td>{decimal(pair.challenger.brier, 4)}</td><td>{decimal((pair.baseline.brier ?? 0) - (pair.challenger.brier ?? 0), 6)}</td></tr>)}</tbody></table></div><p className="fine-print">Foram examinadas 15 configurações no total: Elo, regressão logística, árvores e combinações, além de forma temporal e inatividade. Três controlos com a variável baralhada não reproduziram o ganho. A vantagem no diagnóstico ATP foi pequena e a relva ficou ligeiramente pior. Versão: {report.layoff_research.version}.</p></section>}
    {report?.comparison?.paired_comparison?.xgboost_vs_logistic && <div className="notice amber"><strong>Comparação pareada</strong><span>Intervalo bootstrap por torneio da melhoria de Brier do XGBoost face à logística: {decimal(report.comparison.paired_comparison.xgboost_vs_logistic.cluster_bootstrap_95[0], 6)} a {decimal(report.comparison.paired_comparison.xgboost_vs_logistic.cluster_bootstrap_95[1], 6)}. O teste 2024+ já foi consultado durante esta evolução; a confirmação exige novos dados futuros. Nenhum modelo está aprovado para sinais.</span></div>}
    <div className="notice amber"><strong>Candidato v4</strong><span>O modelo inclui agora serviço e resposta por superfície com regularização e carga de jogos nos 30 dias anteriores. A agenda usa um refit treinado até 2024 e calibrado em 2025 ({report?.operational_version || "por gerar"}); continua em investigação, sem validação de retorno de apostas.</span></div>
    <section className="panel methodology"><div className="section-top"><div><span className="overline">PROTOCOLO</span><h2>Como foi avaliado</h2></div><span className="state-pill">PREDICTION ONLY</span></div><div className="method-grid"><div><strong>01 / Sem informação futura</strong><p>As features são calculadas antes de atualizar o estado com os resultados de cada data de início de torneio.</p></div><div><strong>02 / Simetria</strong><p>O treino inclui as duas orientações do jogo para reduzir dependência da ordem A/B.</p></div><div><strong>03 / Janelas anuais</strong><p>Em cada ano: treino até dois anos antes, calibração no ano anterior e avaliação no seguinte. O desenvolvimento cobre 2019–2023; 2024–2026 é apenas diagnóstico já consultado.</p></div><div><strong>04 / Sem resultado de apostas</strong><p>ROI, CLV, custos e gates de estratégia requerem odds anteriores ao jogo com timestamp e hora real de início.</p></div></div><div className="panel-note">O candidato não substitui as probabilidades diárias. Exige confirmação prospectiva; nenhuma estratégia foi aprovada.</div></section>
  </>;
}

