"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {BASE,decimal,pct} from "../../lib/api";
import {makePlan,Price,Limits} from "../../lib/bankroll";

type Unmodeled={name:string;odds:(number|null)[];url:string;reason:string};
type Snapshot={observed_at:string;source:string;model_note:string;rows:Price[];unmodeled?:Unmodeled[];coverage?:string};
const defaults:Limits={bank:10,perBet:1,total:3,minimum:.5,haircut:5,open:0};
const fields: {key:keyof Limits;label:string;min:number;max:number;step:number}[]=[
  {key:"bank",label:"Banca disponível (€)",min:.01,max:100000,step:.01},
  {key:"minimum",label:"Mínimo da casa (€), a confirmar",min:.01,max:1000,step:.01},
  {key:"open",label:"Montante já em aberto (€)",min:0,max:100000,step:.01},
  {key:"perBet",label:"Limite por aposta (%)",min:.01,max:5,step:.1},
  {key:"total",label:"Limite total em aberto (%)",min:.01,max:10,step:.1},
  {key:"haircut",label:"Margem de prudência (pontos percentuais)",min:0,max:25,step:1},
];
export default function Plan(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState("");
 const [limits,setLimits]=useState(defaults),[query,setQuery]=useState(""),[tour,setTour]=useState("all"),[onlyPositive,setOnlyPositive]=useState(false);
 const [now,setNow]=useState(0),[overrides,setOverrides]=useState<Record<string,string>>({});
 const [checked,setChecked]=useState<string[]>([]);
 async function load(){setError("");try{const r=await fetch(`${BASE}/data/price-comparison.json`,{cache:"no-store"});if(!r.ok)throw Error("Não foi possível carregar as cotações.");setData(await r.json());}catch(e){setError(e instanceof Error?e.message:"Erro de consulta.");}}
 useEffect(()=>{void load();setNow(Date.now());const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const computation=useMemo(()=>{try{return {rows:makePlan((data?.rows||[]).map(row=>({...row,odds:overrides[row.player]!==undefined?Number(overrides[row.player]):row.odds})),limits,now),error:""};}catch(e){return {rows:[],error:e instanceof Error?e.message:"Limites inválidos"};}},[data,limits,now,overrides]);
 const selected=computation.rows.filter(row=>row.simulated>0);
 const simulation=selected.reduce((sum,row)=>sum+row.simulated,0);
 const rows=computation.rows.filter(row=>(tour==="all"||row.tour===tour)&&row.match.toLocaleLowerCase("pt-PT").includes(query.toLocaleLowerCase("pt-PT"))&&(!onlyPositive||row.ev>0));
 const combined=computation.rows.filter(row=>checked.includes(row.player));
 const duplicate=new Set(combined.map(row=>row.fixture_id)).size!==combined.length;
 const comboOdds=combined.reduce((v,r)=>v*r.odds,1),comboP=combined.reduce((v,r)=>v*r.adjusted,1);
 const comboValid=combined.length>=2&&!duplicate&&combined.every(row=>row.valid&&row.fresh&&row.upcoming);
 function download(){const blob=new Blob([JSON.stringify({generated_at:new Date(now).toISOString(),limits,source:data?.source,recommendation:"Exposição real 0 €; plano exploratório",rows:computation.rows},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="plano-tennis-quant.json";a.click();URL.revokeObjectURL(url);}
 return <>
  <div className="page-heading"><div><h1>O teu plano<span className="heading-dot">.</span></h1><p>Cotações dos dois lados, margem de prudência e exposição dentro da banca.</p></div><Link className="button-secondary" href="/hoje">Ver jogos →</Link></div>
  <div className="notice amber"><strong>Exposição real: 0 €</strong><span>O modelo ainda não está aprovado para apostas reais. Os montantes abaixo são simulações: nem Kelly nem uma diferença de preços demonstram rentabilidade.</span></div>
  <section className="panel"><h2>Definir a banca</h2><p className="fine-print">Valores ilustrativos: ¼ Kelly, máximo de 1% por simples e 3% em aberto. O mínimo de 0,50 € é uma hipótese editável, não um mínimo confirmado da Betclic.</p><div className="plan-fields">{fields.map(field=><label key={field.key}>{field.label}<input type="number" min={field.min} max={field.max} step={field.step} value={Number.isNaN(limits[field.key])?"":limits[field.key]} onChange={e=>setLimits({...limits,[field.key]:e.target.value===""?NaN:Number(e.target.value)})}/></label>)}</div>{computation.error&&<p className="form-error" role="alert">{computation.error}</p>}</section>
  <section className="panel plan-summary"><h2>Quanto fica exposto?</h2><dl><div><dt>Limite de cada simples</dt><dd>{decimal(limits.bank*limits.perBet/100)} €</dd></div><div><dt>Disponível no limite total</dt><dd>{decimal(Math.max(0,limits.bank*limits.total/100-limits.open))} €</dd></div><div><dt>Simulação nova</dt><dd>{decimal(simulation)} € · {selected.length} simples</dd></div><div><dt>Montante real indicado</dt><dd>0,00 €</dd></div></dl><p>Se todas as simples simuladas perderem: perda de {decimal(simulation)} €. Se todas ganharem: lucro de {decimal(selected.reduce((sum,row)=>sum+row.simulated*(row.odds-1),0))} €, sujeito às regras de liquidação da casa.</p><p>{selected.length?"A simulação escolhe primeiro os maiores retornos teóricos após prudência, dentro dos limites e com uma seleção por encontro. Esta regra de ordenação não foi validada como estratégia rentável.":"Nenhuma seleção cabe simultaneamente nos critérios e limites. Não aumentar o montante para contornar o mínimo da casa."}</p></section>
  {error&&<div className="notice danger" role="alert">{error}<button className="button-secondary" onClick={()=>void load()}>Tentar novamente</button></div>}
  {!data&&!error&&<p role="status">A carregar a comparação de cotações…</p>}
  {data&&<>
   <section className="panel"><div className="section-top"><div><h2>Comparar todas as seleções</h2><p className="fine-print">{data.source}. Consulta: {new Date(data.observed_at).toLocaleString("pt-PT",{timeZone:"Europe/Lisbon"})}. {data.coverage}</p></div><button className="button-secondary" onClick={download}>Descarregar plano</button></div>
    <p className="fine-print">{data.model_note} Cotações expiram após seis horas. Editar uma cotação cria um cenário manual e não renova a confirmação do mercado.</p>
    <div className="agenda-filters"><label className="agenda-search">Procurar encontro<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jogador ou adversário"/></label><label>Circuito<select value={tour} onChange={e=>setTour(e.target.value)}><option value="all">Todos</option><option>ATP</option><option>WTA</option></select></label><label className="agenda-checkbox"><input type="checkbox" checked={onlyPositive} onChange={e=>setOnlyPositive(e.target.checked)}/>Só vantagem teórica após prudência</label></div>
    <div className="table-scroll"><table className="research-table plan-table"><caption>{rows.length} seleções. Ordenação pelo retorno esperado após prudência. Os filtros só mudam a visualização; o plano usa todo o conjunto.</caption><thead><tr>{["Seleção / encontro","Cotação","Modelo / prudência","Equilíbrio / sem margem","Retorno teórico","Simples simulada / real","Estado","Comparar combinada"].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map(row=>{const counterpart=computation.rows.find(r=>r.fixture_id===row.fixture_id&&r.player!==row.player);const noMargin=counterpart&&row.valid&&counterpart.valid?(1/row.odds)/(1/row.odds+1/counterpart.odds):null;return <tr key={row.player}><th scope="row"><a href={row.url} target="_blank" rel="noreferrer">{row.player} ↗</a><small>{row.match}<br/>{new Date(row.start_at).toLocaleString("pt-PT",{timeZone:"Europe/Lisbon"})}</small></th><td><input aria-label={`Cotação de ${row.player}`} type="number" min="1.01" max="1000" step="0.01" value={overrides[row.player]??row.odds} onChange={e=>setOverrides({...overrides,[row.player]:e.target.value})}/>{overrides[row.player]!==undefined&&<small>Cenário manual</small>}</td><td>{pct(row.probability)} / {pct(row.adjusted)}</td><td>{row.valid?pct(1/row.odds):"—"} / {pct(noMargin)}</td><td>{row.valid?pct(row.ev):"—"}<small>p prudente × cotação − 1</small></td><td>{decimal(row.simulated)} € / 0,00 €</td><td>{row.reason}</td><td><input aria-label={`Comparar ${row.player} em combinada`} type="checkbox" checked={checked.includes(row.player)} disabled={!checked.includes(row.player)&&checked.length>=8} onChange={e=>setChecked(e.target.checked?[...checked,row.player]:checked.filter(p=>p!==row.player))}/></td></tr>;})}</tbody></table></div>{!rows.length&&<p>Nenhuma seleção corresponde aos filtros.</p>}
   </section>
   <section className="panel"><h2>Simples ou combinada?</h2><p>A estrutura de referência é simples: cada resultado e exposição ficam separados. Uma combinada exige que todas as seleções ganhem e pode concentrar o risco. Sistemas repartem o bilhete por mais linhas e não criam vantagem por si só.</p><p>Seleciona entre duas e oito linhas acima para comparar uma combinada. A multiplicação de probabilidades pressupõe independência, que não foi demonstrada.</p>{combined.length>0&&<div className="notice amber"><span>{duplicate?"Seleções do mesmo encontro: combinação inválida; não calculamos probabilidade conjunta.":combined.length<2?"Seleciona pelo menos dois encontros diferentes.":<>{combined.length} seleções · cotação indicativa {decimal(comboOdds,3)} · probabilidade conjunta sob independência {pct(comboP)} · retorno teórico {pct(comboP*comboOdds-1)}. {duplicate?"Seleções do mesmo encontro: combinação inválida.":!comboValid?"Cotações ou horários inválidos/expirados: confirmar antes de qualquer avaliação.":"Mesmo com estas hipóteses, a exposição real indicada permanece em 0 €."}</>}</span></div>}<Link className="text-link" href="/combinadas">Explorar linhas e retornos na calculadora →</Link></section>
   <details className="research-details"><summary>Jogos consultados sem comparação fiável ({data.unmodeled?.length||0})</summary><p>Inclui jogos em direto, pares e encontros sem correspondência única no modelo. Não extrapolamos probabilidades de singulares para pares ou de pré-jogo para direto.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Encontro</th><th>Cotações A / B</th><th>Motivo</th></tr></thead><tbody>{(data.unmodeled||[]).filter(row=>row.name.toLowerCase().includes(query.toLowerCase())).map(row=><tr key={row.url}><td><a href={row.url} target="_blank" rel="noreferrer">{row.name}</a></td><td>{decimal(row.odds[0])} / {decimal(row.odds[1])}</td><td>{row.reason}</td></tr>)}</tbody></table></div></details>
  </>}
  <details className="research-details"><summary>Método, regras e limites do plano</summary><p>Equilíbrio = 1/cotação. Retira-se a margem da casa normalizando as duas probabilidades implícitas. A prudência subtrai os pontos percentuais configurados ao modelo: é um cenário de sensibilidade, não um intervalo de confiança.</p><p>Kelly integral = max(0, (p prudente × cotação − 1)/(cotação − 1)). O plano usa um quarto desse valor, limita cada simples e o total em aberto e arredonda para baixo ao cêntimo. Exclui preços inválidos, expirados, jogos iniciados, vantagem não positiva, seleção repetida do mesmo encontro e montantes abaixo do mínimo.</p><p>Não depositar para cumprir um plano. Não aumentar apostas para recuperar perdas, não usar martingale e não incluir dinheiro necessário para despesas. Uma banca pequena pode inviabilizar os limites por causa do mínimo da casa; nesse caso o plano fica vazio. Os limites são exemplos de gestão de exposição, não parâmetros ótimos comprovados.</p><p>A validação pendente inclui resultados prospectivos congelados, forma e lesões recentes, regras de liquidação/abandono, preços datados e rentabilidade fora da amostra. Nenhuma aposta é enviada pelo site.</p></details>
 </>;
}
